title: Lazuardi N Putra
description: Personal Blog
author: 
  name: "Lazuardi N Putra"
  email: me@laznp.id


theme: minima
minima:
  date_format: "%Y-%m-%d"
  skin: dark
  social_links:
    instagram: papa.gondrong
    telegram: laznp
    linkedin: https://www.linkedin.com/in/lazuardi-np/
include:
  - pages
exclude: 
  - .gitignore
