title: Lazuardi N Putra
description: Personal Blog
url: https://laznp.id
author: "Lazuardi N Putra"
email: me@laznp.id
instagram_username: papa.gondrong
linkedin_username: lazuardi-np
github_username: laznp
